### NUMPY

### Creative Arrays

In [2]:
import numpy as np 
a=np.array([0,1,2,3])

In [3]:
a


array([0, 1, 2, 3])

In [4]:
import numpy as np 
b=np.array(([1.1,1.2,1.3,1.4,1.5,1.6]),dtype= float)

In [5]:
b

array([1.1, 1.2, 1.3, 1.4, 1.5, 1.6])

In [6]:
import numpy as np 
c=np.array([10,20,30,40,50,60,70,80,90,100])

In [7]:
c

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [16]:
k = ([[(1,3,5,7),(6,7,8,9)],[(3,2,1),(2,4,5)]])
k

[[(1, 3, 5, 7), (6, 7, 8, 9)], [(3, 2, 1), (2, 4, 5)]]

### Initial PlaceHolders

In [9]:
k=np.zeros([5,5])
k

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
k= np.ones([3,4])
k

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
k= np.arange(10,30,20)
k

array([10])

In [26]:
k = np.linspace(0,25,60)
k

array([ 0.        ,  0.42372881,  0.84745763,  1.27118644,  1.69491525,
        2.11864407,  2.54237288,  2.96610169,  3.38983051,  3.81355932,
        4.23728814,  4.66101695,  5.08474576,  5.50847458,  5.93220339,
        6.3559322 ,  6.77966102,  7.20338983,  7.62711864,  8.05084746,
        8.47457627,  8.89830508,  9.3220339 ,  9.74576271, 10.16949153,
       10.59322034, 11.01694915, 11.44067797, 11.86440678, 12.28813559,
       12.71186441, 13.13559322, 13.55932203, 13.98305085, 14.40677966,
       14.83050847, 15.25423729, 15.6779661 , 16.10169492, 16.52542373,
       16.94915254, 17.37288136, 17.79661017, 18.22033898, 18.6440678 ,
       19.06779661, 19.49152542, 19.91525424, 20.33898305, 20.76271186,
       21.18644068, 21.61016949, 22.03389831, 22.45762712, 22.88135593,
       23.30508475, 23.72881356, 24.15254237, 24.57627119, 25.        ])

In [28]:
e=np.full((2,8),2)
e


array([[2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2]])

In [29]:
k=np.eye(2)
k

array([[1., 0.],
       [0., 1.]])

In [33]:
k=np.random.random((2,9))
k

array([[0.08350348, 0.12553093, 0.8402024 , 0.41216162, 0.77672499,
        0.30497091, 0.69658359, 0.37395323, 0.3479954 ],
       [0.74649496, 0.48580412, 0.90087761, 0.75247975, 0.2507045 ,
        0.80750291, 0.27660596, 0.65971755, 0.84727378]])

In [34]:
k= np.empty((45,45))
k

array([[1.53208128e-311, 1.53208134e-311, 0.00000000e+000, ...,
        4.45619116e-313, 9.88131292e-323, 1.53309956e-311],
       [0.00000000e+000, 4.94065646e-324, 4.66839074e-313, ...,
        1.53313252e-311, 6.42285340e-323, 1.53313251e-311],
       [5.41990013e-321, 1.53313252e-311, 6.42285340e-323, ...,
        0.00000000e+000, 0.00000000e+000, 4.24399158e-313],
       ...,
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

### Saving & Loading  On Disk 

In [50]:
np.save('my array',k)
k

In [51]:
np.savez('KHIZAR.npz',a,b)
U

In [53]:
np.load('KHIZAR.npz')


### Saving & Loading Text Files 

In [59]:
np.savetxt('KHIZAR.txt',a)
a

array([0, 1, 2, 3])

In [60]:
np.loadtxt("KHIZAR.txt")
k

### INSPECTING YOUR Array

In [61]:
b.size

6

In [63]:
b.shape

(6,)

In [64]:
len(a)

4

In [65]:
b.dtype

dtype('float64')

In [67]:
b.dtype.name

'float64'

In [68]:
b.astype(int)

array([1, 1, 1, 1, 1, 1])

In [69]:
b.astype(float)

array([1.1, 1.2, 1.3, 1.4, 1.5, 1.6])

### Array Mathematics 
### Arithmetic Operations 

In [94]:
a= np.array([0.55,0,0])
b= np.array([3,9,2])
g = a-b 
np.subtract(a,b)

array([-2.45, -9.  , -2.  ])

In [85]:
b[2]

1.3

In [88]:
b[1]

1.2

In [98]:
a= np.array([0.55,0,0])
b= np.array([3,9,2])
g =a*b
np.multiply(a,b)

array([1.65, 0.  , 0.  ])

In [99]:
np.sqrt(b)

array([1.73205081, 3.        , 1.41421356])

In [100]:
np.sin(a)

array([0.52268723, 0.        , 0.        ])

In [101]:
np.cos(b)

array([-0.9899925 , -0.91113026, -0.41614684])

In [102]:
np.log(c)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456, 4.24849524, 4.38202663, 4.49980967, 4.60517019])

In [103]:
np.exp(b)

array([2.00855369e+01, 8.10308393e+03, 7.38905610e+00])

## AGGREGATE

In [104]:
a.sum()

0.55

In [106]:
c.min()

10

In [108]:
c.max(axis=0)

100

In [112]:
b.cumsum(axis=0)

array([ 3, 12, 14], dtype=int32)

In [113]:
c.mean()

55.0

In [114]:
k.mean()

2.0

In [115]:
np.median(b)

3.0

In [116]:
np.corrcoef(k)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2634: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2493: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2493: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)


nan

In [117]:
np.std(k)

0.0

### Sorting Arrays

In [120]:
c.sort()

In [121]:
c.sort(axis=0)

### Subsetting ,Slicing ,Indexing

In [122]:
a[2]

0.55

In [124]:
b[1]

9

In [126]:
a[0:2]
np.array([1,2])

array([1, 2])