TypeError: 'int' object is not subscriptable

In [26]:
a

10

## Slicing

In [32]:
import numpy as np
a=np.array([3,5,6])
b=np.array([(1,2.5,3),(4,5,6)],dtype =float)
c=np.array([[(1,3,5,7),(6,7,8,9)],[(3,2,1),(2,4,5)]])

C:\Users\EMBEDD~1\AppData\Local\Temp/ipykernel_7588/1973643979.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([[(1,3,5,7),(6,7,8,9)],[(3,2,1),(2,4,5)]])


In [33]:
a[::-1]

array([6, 5, 3])

## Bolean

In [34]:
a[a<2]

array([], dtype=int32)

## Fancing indexing

In [35]:
b[[1,0,1,0],[0,1,2,0]]

array([4. , 2.5, 6. , 1. ])

In [37]:
b[[1,0,1,0]],[[0,1,2,0]]

(array([[4. , 5. , 6. ],
        [1. , 2.5, 3. ],
        [4. , 5. , 6. ],
        [1. , 2.5, 3. ]]),
 [[0, 1, 2, 0]])

## ARRAY Manipulation

#### Transposing Array 

In [151]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
i=np.transpose(a)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
i.T

array([3, 5, 6])

#### Changing Array Shape 

In [45]:
b.ravel()

array([1. , 2.5, 3. , 4. , 5. , 6. ])

In [49]:
b.reshape(3,-4)

array([[1. , 2.5],
       [3. , 4. ],
       [5. , 6. ]])

#### Adding /Removing Element 

In [150]:
h=np.array([3,5,4])
h.resize((2,3))
h

array([[3, 5, 4],
       [0, 0, 0]])

In [141]:
np.delete(a,[1])

array([4, 6])

In [142]:
np.insert(a,1,5)

array([4, 5, 5, 6])

In [62]:
np.insert(b,1,6)

array([1. , 6. , 2.5, 3. , 4. , 5. , 6. ])

#### Combining Arrays 

In [120]:
d=np.array([1,2,3])
a=np.array([4,5,6])
np.concatenate((d,a) ,axis=0)


array([1, 2, 3, 4, 5, 6])

In [104]:
np.vstack((a,b))

array([[3. , 5. , 6. ],
       [1. , 2.5, 3. ],
       [4. , 5. , 6. ]])

In [101]:
e=np.array([1,0,4])
f=np.array([3,4,4])
np.r_[e,f]


array([1, 0, 4, 3, 4, 4])

In [102]:
np.column_stack((e,f)) 

array([[1, 3],
       [0, 4],
       [4, 4]])

#### Splitting Array 

In [76]:
np.hsplit(a,3)

[array([3]), array([5]), array([6])]

In [77]:
np.vsplit(c,2)

[array([[(1, 3, 5, 7), (6, 7, 8, 9)]], dtype=object),
 array([[(3, 2, 1), (2, 4, 5)]], dtype=object)]